name: Run tests

on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - 'README.md'
      - 'VERSION.md'
  pull_request:
    branches: [ '*' ]
    paths-ignore:
      - 'README.md'
      - 'VERSION.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    name: Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle and run test
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: test
